# Generated by Django 2.2.10 on 2021-05-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AnonymousUser',
        ),
    ]
