# Generated by Django 2.2.10 on 2021-05-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210529_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ManyToManyField(null=True, related_name='answers', to='api.AnonymousUser'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='one_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_choice', to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='own_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Question'),
        ),
    ]
