# Generated by Django 2.2.10 on 2021-05-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210530_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_name_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
    ]
