# Generated by Django 2.2.10 on 2021-05-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210530_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ManyToManyField(related_name='answers', to='api.Poll'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='several_choice',
            field=models.ManyToManyField(null=True, related_name='several_choice', to='api.Choice'),
        ),
    ]
