# Generated by Django 2.2.10 on 2021-05-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_answer_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_name_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Poll'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='several_choice',
            field=models.ManyToManyField(related_name='several_choice', to='api.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.AnonymousUser'),
        ),
    ]
