# Generated by Django 2.2.10 on 2021-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210530_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='name_id',
            field=models.IntegerField(null=True),
        ),
    ]
