# Generated by Django 2.2.10 on 2021-05-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_anonymoususer_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='one_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_choice', to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='several_choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='several_choice', to='api.Choice'),
        ),
    ]
